CREATE TABLE [dbo].[Book]
(
	[idBook] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[UidBook] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[Shifr] NVARCHAR(256) NOT NULL,
	[NameOfBook] NVARCHAR(256) NOT NULL UNIQUE
)
