CREATE TABLE [dbo].[User]
(
  [idUser] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  [UidUser] UNIQUEIDENTIFIER NOT NULL UNIQUE,
  [Email] NVARCHAR(256) NOT NULL UNIQUE,
  [Name] NVARCHAR(256) NULL,
  [Surname] NVARCHAR(256) NULL,
  [Otchestvo] NVARCHAR(256) NULL,
  [Login] NVARCHAR(256) NOT NULL UNIQUE,
  [Password] NVARCHAR(256) NOT NULL,
  [Address] NVARCHAR(256) NULL,
  [PhoneNumber] NVARCHAR(256) NULL,
  [Age] int NULL,
  [IsAdmin] BIT NOT NULL
)